// <auto-generated />
using Elektronika.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elektronika.Migrations
{
    [DbContext(typeof(ElektronikaContext))]
    [Migration("20220409150529_InitData")]
    partial class InitData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Elektronika.Models.Alkatresz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Beszar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Gyarto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Megnevezes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alkatresz");
                });
#pragma warning restore 612, 618
        }
    }
}
